/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#f7f9fb",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#4e6874",
        "tertiary-container": "#002a1a",
        "primary-container": "#00234b",
        "surface-container": "#eceef0",
        "primary": "#000e24",
        "secondary": "#48626e",
        "tertiary-fixed": "#6ffbbe",
        "on-tertiary-container": "#009e6d",
        "inverse-on-surface": "#eff1f3",
        "secondary-fixed": "#cbe7f5",
        "surface-variant": "#e0e3e5",
        "primary-fixed": "#d6e3ff",
        "surface-container-high": "#e6e8ea",
        "on-tertiary-fixed": "#002113",
        "tertiary-fixed-dim": "#4edea3",
        "on-secondary-fixed-variant": "#304a55",
        "surface-bright": "#f7f9fb",
        "surface-container-low": "#f2f4f6",
        "surface-dim": "#d8dadc",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "on-surface-variant": "#43474e",
        "error-container": "#ffdad6",
        "surface": "#f7f9fb",
        "primary-fixed-dim": "#adc7f8",
        "on-background": "#191c1e",
        "inverse-primary": "#adc7f8",
        "outline-variant": "#c4c6d0",
        "on-error-container": "#93000a",
        "tertiary": "#001209",
        "on-primary-fixed-variant": "#2c4771",
        "on-tertiary-fixed-variant": "#005236",
        "on-primary-container": "#718bb9",
        "on-primary-fixed": "#001b3d",
        "on-secondary-fixed": "#021f29",
        "surface-container-highest": "#e0e3e5",
        "error": "#ba1a1a",
        "inverse-surface": "#2d3133",
        "on-secondary": "#ffffff",
        "surface-tint": "#455f8a",
        "outline": "#74777f",
        "on-surface": "#191c1e",
        "secondary-container": "#cbe7f5",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#afcbd8"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
